// Builds the framework's third-party browser files out of node_modules: the
// nostr bundle, gun and the QR encoder in shared/, and the icon sprite in
// hub/icons.svg. Run `npm install && npm run vendor` after bumping a version,
// then commit the result: nothing is built at page load.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { buildSync } from 'esbuild';

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const nm = (p) => path.join(root, 'node_modules', p);
const version = (pkg) => createRequire(import.meta.url)(nm(`${pkg}/package.json`)).version;
const stripMap = (s) => s.replace(/\n\/\/# sourceMappingURL=.*\s*$/, '\n');

for (const [from, to] of [
  ['gun/gun.js', 'shared/gun.js'],
  ['qrcode-generator/dist/qrcode.mjs', 'shared/qrcode.mjs'],
]) {
  fs.writeFileSync(path.join(root, to), stripMap(fs.readFileSync(nm(from), 'utf8')));
}

/** The sprite every page uses: <svg class="icon"><use href="icons.svg#name"/></svg>. Distributions add their own symbols in icons.svg. */
export const ICONS = [
  'plus', 'minus', 'check', 'x', 'share-2', 'ellipsis', 'trash-2', 'lock', 'globe', 'list-checks', 'notebook-pen', 'package', 'user', 'settings', 'copy',
  'qr-code', 'grip-vertical', 'chevron-left', 'cloud', 'cloud-off', 'download', 'upload', 'key-round', 'eye', 'pencil', 'link', 'sun', 'moon', 'log-out',
  'shield', 'refresh-cw', 'external-link', 'pin', 'pin-off', 'search', 'file-text', 'languages', 'layout-grid', 'send', 'gamepad-2', 'message-square-lock',
  'sticky-note', 'radio-tower', 'git-branch', 'arrow-up-right', 'users', 'user-plus', 'user-check', 'users-round',
];
export function sprite(file, icons) {
  const symbols = icons.map((name) => {
    const svg = fs.readFileSync(nm(`lucide-static/icons/${name}.svg`), 'utf8');
    const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s*\n\s*/g, '');
    return `<symbol id="${name}" viewBox="0 0 24 24">${body}</symbol>`;
  });
  fs.writeFileSync(file, `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n<!-- Lucide icons (ISC) -->\n${symbols.join('\n')}\n</svg>\n`);
  return icons.length;
}
sprite(path.join(root, 'hub/icons.svg'), ICONS);

// The nostr bundle: nostr-tools and its noble/scure dependencies in one ESM file.
buildSync({
  entryPoints: [path.join(root, 'scripts/nostr-entry.mjs')],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  minify: true,
  legalComments: 'none',
  outfile: path.join(root, 'shared/nostr.mjs'),
  banner: { js: `// nostr-tools ${version('nostr-tools')} (Unlicense) with @noble/curves, @noble/hashes, @noble/ciphers, @scure/base (MIT). Built by scripts/vendor.mjs; see shared/LICENSES.md.` },
});

fs.writeFileSync(
  path.join(root, 'shared/LICENSES.md'),
  `# Third-party files in shared/

Generated by \`npm run vendor\` (scripts/vendor.mjs). Do not edit by hand.

| File | Package | License |
|------|---------|---------|
| nostr.mjs | nostr-tools ${version('nostr-tools')} | Unlicense |
| nostr.mjs | @noble/curves ${version('@noble/curves')}, @noble/hashes ${version('@noble/hashes')}, @noble/ciphers ${version('@noble/ciphers')}, @scure/base ${version('@scure/base')} | MIT |
| gun.js | gun ${version('gun')} | Zlib OR MIT OR Apache-2.0 |
| qrcode.mjs | qrcode-generator ${version('qrcode-generator')} | MIT |
| ../hub/icons.svg | lucide-static ${version('lucide-static')} | ISC |
`,
);
console.log(`vendored gun.js, qrcode.mjs, ${ICONS.length} icons and nostr.mjs (${Math.round(fs.statSync(path.join(root, 'shared/nostr.mjs')).size / 1024)} KB)`);
